// app/bharat-darshan/world/data.js
// WORLD MAP — UPSC-focused data layer
// Structured for Countries, Physical Geography, Chokepoints,
// Resources, UPSC Hotspots, Active Recall and Quiz.

export const WORLD_COUNTRIES = [
  ["Afghanistan","Kabul","Asia"],
  ["Albania","Tirana","Europe"],
  ["Algeria","Algiers","Africa"],
  ["Argentina","Buenos Aires","South America"],
  ["Australia","Canberra","Oceania"],
  ["Austria","Vienna","Europe"],
  ["Bangladesh","Dhaka","Asia"],
  ["Belgium","Brussels","Europe"],
  ["Bhutan","Thimphu","Asia"],
  ["Brazil","Brasília","South America"],
  ["Canada","Ottawa","North America"],
  ["Chile","Santiago","South America"],
  ["China","Beijing","Asia"],
  ["Colombia","Bogotá","South America"],
  ["Cuba","Havana","North America"],
  ["Czechia","Prague","Europe"],
  ["Denmark","Copenhagen","Europe"],
  ["Egypt","Cairo","Africa"],
  ["Ethiopia","Addis Ababa","Africa"],
  ["Finland","Helsinki","Europe"],
  ["France","Paris","Europe"],
  ["Germany","Berlin","Europe"],
  ["Ghana","Accra","Africa"],
  ["Greece","Athens","Europe"],
  ["Hungary","Budapest","Europe"],
  ["Iceland","Reykjavík","Europe"],
  ["India","New Delhi","Asia"],
  ["Indonesia","Jakarta","Asia"],
  ["Iran","Tehran","Asia"],
  ["Iraq","Baghdad","Asia"],
  ["Ireland","Dublin","Europe"],
  ["Israel","Jerusalem","Asia"],
  ["Italy","Rome","Europe"],
  ["Japan","Tokyo","Asia"],
  ["Jordan","Amman","Asia"],
  ["Kazakhstan","Astana","Asia"],
  ["Kenya","Nairobi","Africa"],
  ["Kuwait","Kuwait City","Asia"],
  ["Kyrgyzstan","Bishkek","Asia"],
  ["Laos","Vientiane","Asia"],
  ["Lebanon","Beirut","Asia"],
  ["Libya","Tripoli","Africa"],
  ["Malaysia","Kuala Lumpur","Asia"],
  ["Maldives","Malé","Asia"],
  ["Mexico","Mexico City","North America"],
  ["Mongolia","Ulaanbaatar","Asia"],
  ["Morocco","Rabat","Africa"],
  ["Myanmar","Naypyidaw","Asia"],
  ["Nepal","Kathmandu","Asia"],
  ["Netherlands","Amsterdam","Europe"],
  ["New Zealand","Wellington","Oceania"],
  ["Nigeria","Abuja","Africa"],
  ["Norway","Oslo","Europe"],
  ["Oman","Muscat","Asia"],
  ["Pakistan","Islamabad","Asia"],
  ["Peru","Lima","South America"],
  ["Philippines","Manila","Asia"],
  ["Poland","Warsaw","Europe"],
  ["Portugal","Lisbon","Europe"],
  ["Qatar","Doha","Asia"],
  ["Romania","Bucharest","Europe"],
  ["Russia","Moscow","Europe/Asia"],
  ["Saudi Arabia","Riyadh","Asia"],
  ["Serbia","Belgrade","Europe"],
  ["Singapore","Singapore","Asia"],
  ["South Africa","Pretoria","Africa"],
  ["South Korea","Seoul","Asia"],
  ["Spain","Madrid","Europe"],
  ["Sri Lanka","Sri Jayawardenepura Kotte","Asia"],
  ["Sudan","Khartoum","Africa"],
  ["Sweden","Stockholm","Europe"],
  ["Switzerland","Bern","Europe"],
  ["Syria","Damascus","Asia"],
  ["Tajikistan","Dushanbe","Asia"],
  ["Thailand","Bangkok","Asia"],
  ["Tunisia","Tunis","Africa"],
  ["Türkiye","Ankara","Asia/Europe"],
  ["Turkmenistan","Ashgabat","Asia"],
  ["UAE","Abu Dhabi","Asia"],
  ["Uganda","Kampala","Africa"],
  ["Ukraine","Kyiv","Europe"],
  ["United Kingdom","London","Europe"],
  ["United States","Washington, D.C.","North America"],
  ["Uzbekistan","Tashkent","Asia"],
  ["Venezuela","Caracas","South America"],
  ["Vietnam","Hanoi","Asia"],
  ["Yemen","Sana'a","Asia"],
  ["Zambia","Lusaka","Africa"],
  ["Zimbabwe","Harare","Africa"],
];

export const WORLD_PHYSICAL_FEATURES = {
  mountains: [
    ["Himalayas","Asia","India, Nepal, Bhutan, China, Pakistan","Young fold mountain system"],
    ["Karakoram","Asia","Pakistan, India, China","K2; high-altitude passes"],
    ["Hindu Kush","Asia","Afghanistan, Pakistan","Strategic mountain system"],
    ["Tien Shan","Asia","Kyrgyzstan, Kazakhstan, China","Major Central Asian mountain system"],
    ["Kunlun","Asia","China","North of the Tibetan Plateau"],
    ["Zagros","Asia","Iran, Iraq","Major fold mountain system"],
    ["Alps","Europe","France, Switzerland, Italy, Austria","Major European mountain system"],
    ["Pyrenees","Europe","Spain, France, Andorra","Natural barrier between Iberia and France"],
    ["Atlas","Africa","Morocco, Algeria, Tunisia","Northwest African mountain system"],
    ["Drakensberg","Africa","South Africa, Lesotho","Southern African mountain system"],
    ["Andes","South America","Chile, Argentina, Peru, Bolivia, Ecuador, Colombia, Venezuela","Major western South American mountain chain"],
    ["Rockies","North America","Canada, United States","Western North American mountain system"],
    ["Appalachians","North America","United States, Canada","Ancient mountain system"],
    ["Great Dividing Range","Oceania","Australia","Eastern Australian mountain system"],
  ],

  rivers: [
    ["Nile","Africa","Lake Victoria region","Mediterranean Sea","Egypt, Sudan, Uganda and basin states"],
    ["Amazon","South America","Peruvian Andes","Atlantic Ocean","Brazil, Peru, Colombia and basin"],
    ["Yangtze","Asia","Tibetan Plateau","East China Sea","China"],
    ["Yellow River","Asia","Qinghai/Tibetan Plateau","Bohai Sea","China"],
    ["Mekong","Asia","Tibetan Plateau","South China Sea","China, Myanmar, Laos, Thailand, Cambodia, Vietnam"],
    ["Ganges","Asia","Himalayas","Bay of Bengal","India, Bangladesh"],
    ["Brahmaputra","Asia","Tibet","Bay of Bengal","China, India, Bangladesh"],
    ["Indus","Asia","Tibetan Plateau","Arabian Sea","China, India, Pakistan"],
    ["Tigris","Asia","Turkey","Persian Gulf system","Turkey, Iraq"],
    ["Euphrates","Asia","Turkey","Persian Gulf system","Turkey, Syria, Iraq"],
    ["Danube","Europe","Germany","Black Sea","Central and Eastern Europe"],
    ["Rhine","Europe","Swiss Alps","North Sea","Switzerland, Germany, Netherlands"],
    ["Volga","Europe","Russia","Caspian Sea","Russia"],
    ["Niger","Africa","Guinea Highlands region","Gulf of Guinea","West Africa"],
    ["Congo","Africa","Central Africa","Atlantic Ocean","DR Congo, Republic of Congo and basin"],
    ["Zambezi","Africa","Southern Africa","Indian Ocean","Zambia, Zimbabwe, Mozambique and basin"],
    ["Orange","Africa","Lesotho/South Africa","Atlantic Ocean","Southern Africa"],
    ["Paraná","South America","Brazil","Río de la Plata","Brazil, Paraguay, Argentina"],
    ["Orinoco","South America","Venezuela region","Atlantic Ocean","Venezuela, Colombia basin"],
    ["Mississippi–Missouri","North America","United States","Gulf of Mexico","United States"],
    ["Mackenzie","North America","Canada","Beaufort Sea","Canada"],
    ["Murray–Darling","Oceania","Australia","Southern Ocean system","Australia"],
  ],

  straits: [
    ["Strait of Hormuz","Persian Gulf ↔ Gulf of Oman","Iran–Oman/UAE vicinity","Major oil-shipping chokepoint"],
    ["Strait of Malacca","Andaman Sea ↔ South China Sea","Malaysia–Indonesia–Singapore","Major Indo-Pacific trade route"],
    ["Bab-el-Mandeb","Red Sea ↔ Gulf of Aden","Yemen–Djibouti/Eritrea","Gateway to Suez route"],
    ["Bosporus","Black Sea ↔ Sea of Marmara","Türkiye","Separates European and Asian Türkiye"],
    ["Dardanelles","Aegean Sea ↔ Sea of Marmara","Türkiye","Access to Black Sea through Turkish Straits"],
    ["Strait of Gibraltar","Atlantic ↔ Mediterranean","Spain–Morocco","Gateway between Atlantic and Mediterranean"],
    ["Bering Strait","Arctic Ocean ↔ Pacific","Russia–United States","Separates Asia and North America"],
    ["Taiwan Strait","East China Sea ↔ South China Sea","China–Taiwan","Strategic East Asian waterway"],
    ["Korea Strait","East China Sea ↔ Sea of Japan/East Sea","Korea–Japan","Northeast Asian maritime route"],
    ["Dover Strait","English Channel","United Kingdom–France","Narrowest part of English Channel"],
    ["Palk Strait","Bay of Bengal","India–Sri Lanka","South Asian strait"],
    ["Sunda Strait","Java Sea ↔ Indian Ocean","Indonesia","Between Java and Sumatra"],
    ["Lombok Strait","Bali Sea ↔ Indian Ocean","Indonesia","Deep Indonesian passage"],
    ["Makassar Strait","Celebes Sea ↔ Java Sea","Indonesia","Between Borneo and Sulawesi"],
    ["Torres Strait","Arafura Sea ↔ Coral Sea","Australia–Papua New Guinea","Between Australia and New Guinea"],
  ],

  seas: [
    ["Mediterranean Sea","Atlantic-connected marginal sea","Europe–Africa–Asia"],
    ["Black Sea","Atlantic-connected inland sea","Eastern Europe–West Asia"],
    ["Red Sea","Indian Ocean marginal sea","Northeast Africa–Arabia"],
    ["Arabian Sea","Northern Indian Ocean","India–Arabian Peninsula–East Africa"],
    ["South China Sea","Western Pacific marginal sea","Southeast Asia"],
    ["East China Sea","Western Pacific marginal sea","China–Korea–Japan region"],
    ["Sea of Japan / East Sea","Western Pacific marginal sea","Japan–Korean Peninsula–Russia"],
    ["Caribbean Sea","Atlantic marginal sea","Caribbean–Central America–South America"],
    ["North Sea","Atlantic marginal sea","Northwestern Europe"],
    ["Baltic Sea","Northern European sea","Northern Europe"],
    ["Bering Sea","North Pacific marginal sea","Russia–Alaska"],
    ["Coral Sea","South Pacific marginal sea","Australia–Melanesia"],
    ["Tasman Sea","South Pacific sea","Australia–New Zealand"],
  ],

  gulfs: [
    ["Gulf of Mexico","Atlantic","United States–Mexico–Cuba"],
    ["Gulf of Guinea","Atlantic","West Africa"],
    ["Persian Gulf","Indian Ocean system","Iran–Arabian Peninsula"],
    ["Gulf of Oman","Arabian Sea system","Iran–Oman–UAE/Pakistan vicinity"],
    ["Gulf of Aden","Indian Ocean system","Yemen–Somalia/Djibouti"],
    ["Gulf of Thailand","South China Sea","Thailand–Cambodia–Vietnam–Malaysia"],
    ["Gulf of Mannar","Indian Ocean","India–Sri Lanka"],
    ["Gulf of California","Pacific","Mexico"],
    ["Gulf of Bothnia","Baltic Sea","Sweden–Finland"],
  ],

  canals: [
    ["Suez Canal","Egypt","Mediterranean Sea ↔ Red Sea","Europe–Asia maritime shortcut"],
    ["Panama Canal","Panama","Atlantic ↔ Pacific","Interoceanic canal"],
    ["Kiel Canal","Germany","North Sea ↔ Baltic Sea","European maritime shortcut"],
    ["Corinth Canal","Greece","Gulf of Corinth ↔ Saronic Gulf","Cuts across the Isthmus of Corinth"],
  ],

  deserts: [
    ["Sahara","Africa","North Africa","Largest hot desert"],
    ["Arabian Desert","Asia","Arabian Peninsula","Arid West Asia"],
    ["Gobi","Asia","Mongolia–China","Cold desert"],
    ["Taklamakan","Asia","Xinjiang, China","Tarim Basin desert"],
    ["Thar","Asia","India–Pakistan","Monsoon-influenced desert"],
    ["Karakum","Asia","Turkmenistan","Central Asian desert"],
    ["Kyzylkum","Asia","Uzbekistan–Kazakhstan","Central Asian desert"],
    ["Atacama","South America","Chile–Peru region","Extremely arid coastal desert"],
    ["Patagonian Desert","South America","Argentina","Cold desert"],
    ["Namib","Africa","Namibia–Angola–South Africa region","Coastal desert"],
    ["Kalahari","Africa","Botswana–Namibia–South Africa","Semi-arid region"],
    ["Great Victoria Desert","Australia","Western/Southern Australia","Australian desert"],
    ["Great Sandy Desert","Australia","Western Australia","Australian desert"],
    ["Mojave","North America","United States","Southwestern US"],
  ],

  lakes: [
    ["Caspian Sea","Europe/Asia","Largest enclosed inland water body by area"],
    ["Lake Baikal","Asia","Russia","Deep freshwater lake"],
    ["Lake Victoria","Africa","Tanzania–Uganda–Kenya","Major Nile-system lake"],
    ["Lake Tanganyika","Africa","Tanzania–DR Congo–Burundi–Zambia","Very deep African lake"],
    ["Lake Superior","North America","United States–Canada","Largest Great Lake by area"],
    ["Lake Titicaca","South America","Peru–Bolivia","High-altitude navigable lake"],
    ["Aral Sea","Asia","Kazakhstan–Uzbekistan","Major environmental-change case study"],
    ["Dead Sea","Asia","Israel/West Bank–Jordan region","Hypersaline lake"],
  ],
};

export const WORLD_RESOURCES = [
  ["Persian Gulf","Petroleum & natural gas","West Asia","Hormuz is the key chokepoint"],
  ["North Sea","Petroleum & natural gas","Europe","Offshore resources"],
  ["Gulf of Mexico","Petroleum & natural gas","North America","Offshore production"],
  ["West Siberia","Petroleum & natural gas","Russia","Major Eurasian hydrocarbon province"],
  ["Middle East","Petroleum & natural gas","West Asia","Major global hydrocarbon region"],
  ["Silesia","Coal","Poland/Czechia region","European coal belt"],
  ["Appalachian Basin","Coal","United States","Major North American coal province"],
  ["Bowen Basin","Coal","Australia","Important Australian coal region"],
  ["Pilbara","Iron ore","Australia","Major iron-ore province"],
  ["Carajás","Iron ore","Brazil","Major iron-ore province"],
  ["Copperbelt","Copper","Zambia–DR Congo","Major copper/cobalt belt"],
  ["Atacama","Copper","Chile","Major global copper region"],
  ["Lithium Triangle","Lithium","Argentina–Bolivia–Chile","Major salt-flat lithium region"],
  ["Guiana Shield","Bauxite/iron ore","South America","Resource-rich shield region"],
];

export const WORLD_UPSC_HOTSPOTS = [
  ["Strait of Hormuz","West Asia","Energy security + maritime chokepoint"],
  ["Strait of Malacca","Southeast Asia","Trade route + Indo-Pacific"],
  ["Bab-el-Mandeb","Red Sea region","Suez route + maritime security"],
  ["Suez Canal","Egypt","Europe–Asia trade route"],
  ["Panama Canal","Central America","Atlantic–Pacific connectivity"],
  ["South China Sea","Southeast Asia","Trade, resources + geopolitics"],
  ["Taiwan Strait","East Asia","Strategic maritime geography"],
  ["Arctic","Polar region","New routes + resources + climate"],
  ["Black Sea","Europe–West Asia","Trade, security + riverine geography"],
  ["Horn of Africa","Northeast Africa","Red Sea/Gulf of Aden gateway"],
  ["Sahel","Africa","Desertification + security + climate"],
  ["Great Lakes of Africa","East/Central Africa","Water, population + resources"],
  ["Andes","South America","Climate, glaciers + minerals"],
  ["Amazon Basin","South America","Biodiversity + carbon cycle"],
  ["Caspian region","Central Asia","Energy + transport corridors"],
];

export const WORLD_ACTIVE_RECALL = [
  ["Strait of Hormuz","Which waterway connects the Persian Gulf with the Gulf of Oman?"],
  ["Strait of Malacca","Which strait is a major maritime route between the Indian and Pacific Ocean systems?"],
  ["Bab-el-Mandeb","Which strait links the Red Sea with the Gulf of Aden?"],
  ["Strait of Gibraltar","Which strait connects the Atlantic Ocean with the Mediterranean Sea?"],
  ["Bering Strait","Which strait separates Russia from Alaska?"],
  ["Suez Canal","Which canal connects the Mediterranean Sea with the Red Sea?"],
  ["Panama Canal","Which canal connects the Atlantic and Pacific maritime systems?"],
  ["Atacama","Which South American desert is famous for extreme aridity?"],
  ["Gobi","Which major desert lies across Mongolia and northern China?"],
  ["Andes","Which mountain system runs along the western margin of South America?"],
  ["Danube","Which major European river flows into the Black Sea?"],
  ["Amazon","Which major South American river drains into the Atlantic Ocean?"],
  ["Mekong","Which major Southeast Asian river flows through multiple mainland Southeast Asian countries?"],
  ["Caspian Sea","Which enclosed water body is the world's largest inland water body by area?"],
  ["Lake Baikal","Which Russian lake is famous for exceptional depth and freshwater volume?"],
];

export const WORLD_QUIZ = [
  {
    q:"Which strait connects the Persian Gulf with the Gulf of Oman?",
    o:["Malacca","Hormuz","Gibraltar","Bering"],
    a:1,
    e:"The Strait of Hormuz is the gateway between the Persian Gulf and Gulf of Oman."
  },
  {
    q:"Bab-el-Mandeb connects the Red Sea with the:",
    o:["Gulf of Aden","Persian Gulf","Bay of Bengal","Black Sea"],
    a:0,
    e:"It lies at the southern entrance of the Red Sea."
  },
  {
    q:"The Suez Canal connects the Mediterranean Sea with the:",
    o:["Arabian Sea","Red Sea","Black Sea","Caspian Sea"],
    a:1,
    e:"The canal provides the maritime link between the Mediterranean and Red Sea."
  },
  {
    q:"Which mountain system lies along the western edge of South America?",
    o:["Rockies","Andes","Alps","Atlas"],
    a:1,
    e:"The Andes form the dominant mountain chain along western South America."
  },
  {
    q:"The Atacama Desert is mainly associated with:",
    o:["Chile","Egypt","Mongolia","Australia"],
    a:0,
    e:"The Atacama is principally in northern Chile, with extension toward Peru."
  },
  {
    q:"Which river flows into the Black Sea?",
    o:["Danube","Nile","Mekong","Orange"],
    a:0,
    e:"The Danube empties into the Black Sea delta."
  },
  {
    q:"The Strait of Malacca lies between:",
    o:["Spain and Morocco","Malaysia and Sumatra/Indonesia","Russia and Alaska","India and Sri Lanka"],
    a:1,
    e:"It is the major passage between the Malay Peninsula and Sumatra."
  },
  {
    q:"Lake Baikal is located in:",
    o:["Russia","Canada","Peru","Kenya"],
    a:0,
    e:"Lake Baikal is in southern Siberia, Russia."
  },
  {
    q:"The Gobi Desert extends across:",
    o:["Mongolia and China","India and Pakistan","Namibia and Botswana","Chile and Peru"],
    a:0,
    e:"The Gobi occupies southern Mongolia and northern China."
  },
  {
    q:"The Panama Canal links the Atlantic and:",
    o:["Indian Ocean","Pacific Ocean","Arctic Ocean","Southern Ocean"],
    a:1,
    e:"It provides an interoceanic route between Atlantic and Pacific systems."
  },
  {
    q:"The Copperbelt is strongly associated with:",
    o:["Zambia and DR Congo","Spain and Portugal","Canada and USA","India and Nepal"],
    a:0,
    e:"The Central African Copperbelt spans Zambia and the DR Congo region."
  },
  {
    q:"The Lithium Triangle is located mainly in:",
    o:["South America","Central Africa","Southeast Asia","Eastern Europe"],
    a:0,
    e:"It broadly refers to lithium-rich salt-flat regions of Argentina, Bolivia and Chile."
  },
];

export const WORLD_LEARNING_MODES = [
  {id:"countries",label:"Countries & Capitals",icon:"🌐"},
  {id:"mountains",label:"Mountains & Peaks",icon:"⛰️"},
  {id:"rivers",label:"Rivers",icon:"🌊"},
  {id:"straits",label:"Straits & Chokepoints",icon:"🚢"},
  {id:"seas",label:"Seas & Gulfs",icon:"🌍"},
  {id:"deserts",label:"Deserts",icon:"🏜️"},
  {id:"lakes",label:"Lakes",icon:"💧"},
  {id:"resources",label:"Resources",icon:"⛏️"},
  {id:"hotspots",label:"UPSC Hotspots",icon:"📍"},
];

export const WORLD_STATS = {
  countryEntries: WORLD_COUNTRIES.length,
  mountainEntries: WORLD_PHYSICAL_FEATURES.mountains.length,
  riverEntries: WORLD_PHYSICAL_FEATURES.rivers.length,
  straitEntries: WORLD_PHYSICAL_FEATURES.straits.length,
  seaEntries: WORLD_PHYSICAL_FEATURES.seas.length,
  gulfEntries: WORLD_PHYSICAL_FEATURES.gulfs.length,
  canalEntries: WORLD_PHYSICAL_FEATURES.canals.length,
  desertEntries: WORLD_PHYSICAL_FEATURES.deserts.length,
  lakeEntries: WORLD_PHYSICAL_FEATURES.lakes.length,
  resourceEntries: WORLD_RESOURCES.length,
  hotspotEntries: WORLD_UPSC_HOTSPOTS.length,
};

export default {
  WORLD_COUNTRIES,
  WORLD_PHYSICAL_FEATURES,
  WORLD_RESOURCES,
  WORLD_UPSC_HOTSPOTS,
  WORLD_ACTIVE_RECALL,
  WORLD_QUIZ,
  WORLD_LEARNING_MODES,
  WORLD_STATS,
};
